'use client';

import { useState } from 'react';
import { motion } from 'framer-motion';
import { Copy, Check, Download, FileCode, ChevronDown, ChevronUp, Sparkles, Mail, Globe, Shield, Monitor, KeyRound } from 'lucide-react';

interface EnvVar {
  key: string;
  description: string;
  example: string;
  required: boolean;
  category: string;
  icon: React.ComponentType<any>;
  link?: string;
  linkText?: string;
}

const envVars: EnvVar[] = [
  {
    key: 'NEXT_PUBLIC_SUPABASE_URL',
    description: 'Your Supabase project URL',
    example: 'https://your-project.supabase.co',
    required: true,
    category: 'Core',
    icon: KeyRound,
  },
  {
    key: 'NEXT_PUBLIC_SUPABASE_ANON_KEY',
    description: 'Your Supabase anonymous/public key',
    example: 'eyJhbGciOiJIUzI1NiIs...',
    required: true,
    category: 'Core',
    icon: KeyRound,
  },
  {
    key: 'SUPABASE_SERVICE_ROLE_KEY',
    description: 'Your Supabase service role key (server-side only)',
    example: 'eyJhbGciOiJIUzI1NiIs...',
    required: true,
    category: 'Core',
    icon: KeyRound,
  },
  {
    key: 'GROQ_API_KEY',
    description: 'Groq AI API key for title/description/price optimization',
    example: 'gsk_xxxxxxxxxxxx',
    required: false,
    category: 'AI',
    icon: Sparkles,
    link: 'https://console.groq.com/keys',
    linkText: 'Get Groq API Key',
  },
  {
    key: 'RESEND_API_KEY',
    description: 'Resend API key for email notifications',
    example: 're_xxxxxxxxxxxx',
    required: false,
    category: 'Email',
    icon: Mail,
    link: 'https://resend.com/api-keys',
    linkText: 'Get Resend API Key',
  },
  {
    key: 'BROWSERBASE_API_KEY',
    description: 'Browserbase API key for cloud browser automation',
    example: 'bb_xxxxxxxxxxxx',
    required: false,
    category: 'Browser',
    icon: Globe,
    link: 'https://browserbase.com/settings',
    linkText: 'Get Browserbase Key',
  },
  {
    key: 'BROWSERBASE_PROJECT_ID',
    description: 'Browserbase project ID',
    example: 'proj_xxxxxxxx',
    required: false,
    category: 'Browser',
    icon: Globe,
  },
  {
    key: 'FACEBOOK_APP_ID',
    description: 'Facebook App ID for OAuth integration',
    example: '1234567890123456',
    required: false,
    category: 'Social',
    icon: Shield,
    link: 'https://developers.facebook.com/apps',
    linkText: 'Create Facebook App',
  },
  {
    key: 'FACEBOOK_APP_SECRET',
    description: 'Facebook App Secret for OAuth integration',
    example: 'abc123def456...',
    required: false,
    category: 'Social',
    icon: Shield,
  },
  {
    key: 'ENCRYPTION_KEY',
    description: '32-character encryption key for credential storage (auto-generated OK)',
    example: 'your-32-char-encryption-key-here!',
    required: true,
    category: 'Security',
    icon: KeyRound,
  },
  {
    key: 'USE_CLOAK_BROWSER',
    description: 'Use CloakBrowser for local automation (true/false)',
    example: 'false',
    required: false,
    category: 'Browser',
    icon: Monitor,
  },
];

export default function EnvGenerator() {
  const [values, setValues] = useState<Record<string, string>>({});
  const [copied, setCopied] = useState(false);
  const [expandedCats, setExpandedCats] = useState<Set<string>>(new Set(['Core', 'Security']));

  const categories = [...new Set(envVars.map(v => v.category))];

  const toggleCat = (cat: string) => {
    const next = new Set(expandedCats);
    if (next.has(cat)) next.delete(cat);
    else next.add(cat);
    setExpandedCats(next);
  };

  const generateEnv = () => {
    const lines: string[] = ['# ThriftList Environment Configuration', '# Generated by Setup Wizard', ''];
    categories.forEach(cat => {
      const catVars = envVars.filter(v => v.category === cat);
      if (catVars.length === 0) return;
      lines.push(`# ${cat}`);
      catVars.forEach(v => {
        const val = values[v.key] || v.example;
        lines.push(`${v.key}=${val}`);
      });
      lines.push('');
    });
    return lines.join('\n');
  };

  const copyToClipboard = async () => {
    await navigator.clipboard.writeText(generateEnv());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadFile = () => {
    const blob = new Blob([generateEnv()], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = '.env.local';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-4">
      <div className="rounded-xl border border-white/[0.04] bg-[#111111] p-4 space-y-3">
        <p className="text-xs text-white/40">
          Fill in your API keys below. We&apos;ll generate a ready-to-use <code className="text-accent">.env.local</code> file.
        </p>

        {categories.map(cat => {
          const catVars = envVars.filter(v => v.category === cat);
          const isOpen = expandedCats.has(cat);
          return (
            <div key={cat} className="border border-white/[0.04] rounded-lg overflow-hidden">
              <button
                onClick={() => toggleCat(cat)}
                className="w-full flex items-center justify-between px-3 py-2 bg-white/[0.02] hover:bg-white/[0.04] transition-colors"
              >
                <span className="text-xs font-semibold uppercase tracking-wider text-white/50">{cat}</span>
                {isOpen ? <ChevronUp className="w-3.5 h-3.5 text-white/30" /> : <ChevronDown className="w-3.5 h-3.5 text-white/30" />}
              </button>
              {isOpen && (
                <div className="p-3 space-y-3">
                  {catVars.map(v => (
                    <div key={v.key}>
                      <div className="flex items-center gap-2 mb-1">
                        <v.icon className="w-3.5 h-3.5 text-white/30" />
                        <label className="text-[11px] font-semibold uppercase tracking-wider text-white/50">
                          {v.key}
                          {v.required && <span className="text-red-400 ml-1">*</span>}
                        </label>
                        {v.link && (
                          <a
                            href={v.link}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="text-[10px] text-accent hover:underline ml-auto"
                          >
                            {v.linkText}
                          </a>
                        )}
                      </div>
                      <input
                        type="text"
                        value={values[v.key] || ''}
                        onChange={e => setValues(s => ({ ...s, [v.key]: e.target.value }))}
                        placeholder={v.example}
                        className="w-full px-3 py-2 rounded-lg border border-white/10 bg-[#0c0c0c] text-white text-xs placeholder-white/20 focus:outline-none focus:border-accent/50 font-mono"
                      />
                      <p className="text-[10px] text-white/30 mt-1">{v.description}</p>
                    </div>
                  ))}
                </div>
              )}
            </div>
          );
        })}
      </div>

      {/* Preview */}
      <div className="rounded-xl border border-white/[0.04] bg-[#0c0c0c] p-4 space-y-3">
        <div className="flex items-center gap-2">
          <FileCode className="w-4 h-4 text-accent" />
          <span className="text-xs font-semibold uppercase tracking-wider text-white/40">Generated .env.local</span>
        </div>
        <pre className="text-[10px] text-white/40 font-mono bg-black/30 rounded-lg p-3 overflow-x-auto whitespace-pre-wrap">
          {generateEnv()}
        </pre>
        <div className="flex gap-2">
          <button
            onClick={copyToClipboard}
            className="flex-1 inline-flex items-center justify-center gap-2 px-3 py-2 bg-accent/10 text-accent rounded-lg text-xs hover:bg-accent/20 transition-colors"
          >
            {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
            {copied ? 'Copied!' : 'Copy to Clipboard'}
          </button>
          <button
            onClick={downloadFile}
            className="flex-1 inline-flex items-center justify-center gap-2 px-3 py-2 border border-white/10 text-white/60 rounded-lg text-xs hover:bg-white/5 transition-colors"
          >
            <Download className="w-3.5 h-3.5" />
            Download File
          </button>
        </div>
      </div>

      <div className="flex items-start gap-2 text-xs text-white/30">
        <KeyRound className="w-3.5 h-3.5 flex-shrink-0 mt-0.5" />
        <p>
          <strong className="text-white/50">Security note:</strong> Keep this file private. Never commit <code className="text-accent">.env.local</code> to Git. Add it to <code className="text-accent">.gitignore</code>.
        </p>
      </div>
    </div>
  );
}
